rootProject.name = 'log4key'

include 'log4key-api'
include 'log4key-core'
include 'samples:log4key-quick-start'
include 'samples:log4key-spring-boot-simple'
include 'samples:log4key-config-sample'
findProject(':samples:log4key-quick-start')?.name = 'log4key-quick-start'
findProject(':samples:log4key-spring-boot-simple')?.name = 'log4key-spring-boot-simple'
findProject(':samples:log4key-config-sample')?.name = 'log4key-config-sample'

