/*
 * Copyright 2026 Log4Key
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */
package com.log4key.metrics;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Log metrics collector.
 *
 * 日志指标采集器。
 */
public class LogMetrics {

    /**
     * 是否接受数据
     */
    private static volatile boolean accepting = true;

    /**
     * Produced events，反映产生的或接收的事件数
     */
    public static final AtomicLong PRODUCED_EVENTS = new AtomicLong();

    /**
     * Routed Events，通过路由拆解处理，产生的实际需要处理的事件数
     */
    public static final AtomicLong ROUTED_EVENTS = new AtomicLong();

    /**
     * Consumed Events，Worker 从邮箱中取出事件进行处理的数量
     */
    public static final AtomicLong CONSUMED_EVENTS = new AtomicLong();

    /**
     * Rejected Events，Mailbox 满导致事件被拒绝的数量
     */
    public static final AtomicLong REJECTED_EVENTS = new AtomicLong();

    /**
     * Records a log event.
     *
     * 记录日志事件数。
     */
    public static void recordEvent() {
        if (accepting) {
            PRODUCED_EVENTS.incrementAndGet();
        }
    }

    /**
     * Records the number of files generated by an event.
     *
     * 记录文件数，一个事件可因为日志级别而产生多个文件。
     *
     * @param files the number of files / 文件数
     */
    public static void recordFile(long files) {
        if (accepting) {
            ROUTED_EVENTS.addAndGet(files);
        }
    }

    /**
     * Records a consumed event.
     *
     * 记录 Worker 消费的事件数。
     */
    public static void recordConsumed() {
        if (accepting) {
            CONSUMED_EVENTS.incrementAndGet();
        }
    }

    /**
     * Records a rejected event.
     *
     * 记录被拒绝的事件数。
     */
    public static void recordRejected() {
        if (accepting) {
            REJECTED_EVENTS.incrementAndGet();
        }
    }

    /**
     * Gets the total number of produced events.
     *
     * 获取产生的总事件数。
     *
     * @return the total number of produced events / 产生的总事件数
     */
    public static long getProducedEvents() {
        return PRODUCED_EVENTS.get();
    }

    /**
     * Gets the total number of routed events.
     *
     * 获取路由处理后的事件数。
     *
     * @return the number of routed events / 路由事件数
     */
    public static long getRoutedEvents() {
        return ROUTED_EVENTS.get();
    }

    /**
     * Gets the total number of consumed events.
     *
     * 获取 Worker 消费的总事件数。
     *
     * @return the number of consumed events / 消费事件数
     */
    public static long getConsumedEvents() {
        return CONSUMED_EVENTS.get();
    }

    /**
     * Gets the total number of rejected events.
     *
     * 获取被拒绝的总事件数。
     *
     * @return the number of rejected events / 拒绝事件数
     */
    public static long getRejectedEvents() {
        return REJECTED_EVENTS.get();
    }

    /**
     * Disables metrics collection.
     *
     * 拒绝数据采集，用于测试或暂停采集。
     */
    public static void refuse() {
        accepting = false;
    }

    /**
     * Resets all counters.
     *
     * 重置所有计数器，用于测试或重新开始采集。
     */
    public static void reset() {
        accepting = true;
        PRODUCED_EVENTS.set(0);
        ROUTED_EVENTS.set(0);
        CONSUMED_EVENTS.set(0);
        REJECTED_EVENTS.set(0);
    }

    /**
     * 显示所有计数指标
     */
    public static String info() {
        return "PRODUCED_EVENTS:" + PRODUCED_EVENTS.get() + "\n" +
                "ROUTED_EVENTS:" + ROUTED_EVENTS.get() + "\n" +
                "CONSUMED_EVENTS:" + CONSUMED_EVENTS.get() + "\n" +
                "REJECTED_EVENTS:" + REJECTED_EVENTS.get();
    }

}