/*
 * Copyright 2026 Log4Key
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */
package com.log4key.metrics;

import java.util.concurrent.atomic.AtomicLong;

/**
 * Log metrics collector.
 *
 * 日志指标采集器。
 */
public class LogMetrics {

    /**
     * 是否接受数据
     */
    private static volatile boolean accepting = true;

    /**
     * 接收的事件数
     */
    public static final AtomicLong ACCEPT_EVENTS = new AtomicLong();

    /**
     * 根据事件产生的文件数
     */
    public static final AtomicLong EVENT_FILES = new AtomicLong();

    /**
     * Records a log event.
     *
     * 记录日志事件数。
     */
    public static void recordEvent() {
        if (accepting) {
            ACCEPT_EVENTS.incrementAndGet();
        }
    }

    /**
     * Records the number of files generated by an event.
     *
     * 记录文件数，一个事件可因为日志级别而产生多个文件。
     *
     * @param files the number of files / 文件数
     */
    public static void recordFile(long files) {
        if (accepting) {
            EVENT_FILES.addAndGet(files);
        }
    }

    /**
     * Gets the total number of accepted events.
     *
     * 获取总日志事件数。
     *
     * @return the total number of events / 总日志事件数
     */
    public static long getAcceptEvents() {
        return ACCEPT_EVENTS.get();
    }

    /**
     * Gets the total number of event files.
     *
     * 获取文件数。
     *
     * @return the number of event files / 文件数
     */
    public static long getEventFiles() {
        return EVENT_FILES.get();
    }

    /**
     * Disables metrics collection.
     *
     * 拒绝数据采集，用于测试或暂停采集。
     */
    public static void refuse() {
        accepting = false;
    }

    /**
     * Resets all counters.
     *
     * 重置所有计数器，用于测试或重新开始采集。
     */
    public static void reset() {
        accepting = true;
        ACCEPT_EVENTS.set(0);
        EVENT_FILES.set(0);
    }

    /**
     * 显示所有计数指标
     */
    public static String info() {
        return "ACCEPT_EVENTS:" + ACCEPT_EVENTS.get() + "\n" +
                "EVENT_FILES:" + EVENT_FILES.get();
    }

}
