plugins {
    id 'application'
}

group = 'com.log4key.sample'
version = '1.0.0'
sourceCompatibility = '1.8'

dependencies {
    implementation 'com.log4key:log4key-all:0.1.3'
    // Gson解析依赖
    implementation "com.google.code.gson:gson:2.10.1"
}

application {
    mainClass = "com.log4key.sample.ConfigSampleApplication"
}